### PR TITLE
Add link to silicon DMG on install page

### PR DESCRIPTION
**Pull request by Carifio24**
Alyssa had asked me to put a link to the silicon DMG on the site, so this PR does that.

### CODE REVIEW

**Comment by astrofrog** [comment]
Oh for some reason I thought the latest build was already the silicone one? Will double check.

**Comment by Carifio24** [comment]
I thought the 2023.06.4 one was not the silicon build, but feel free to close this if I'm wrong.

**Comment by astrofrog** [comment]
Oh wait yes that's ancient but the most recent stable version might be silicone. Will check.

**Comment by Carifio24** [comment]
Cool, LMK if there are updated versions (for either Intel or silicon) and I'll update the links here.

**Comment by astrofrog** [comment]
Sorry for not getting back to you sooner. This version:

http://glueviz.s3.amazonaws.com/installers/download.html?prefix=installers/2024.03.1/

is silicone-only for the MacOS X. Maybe we can advertise that as the primary link and point Intel users to the previously advertised stable version.

**Comment by Carifio24** [comment]
@astrofrog I updated the MacOS silicon and Windows links to point to the 2024.03.1 builds (and left MacOS as 2023.06.4).

**Comment by Carifio24** [comment]
@astrofrog Just wanted to check whether we're good with these links now?

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
